### ISSUE TITLE
1.92不支持吗

### ISSUE THREAD

**Issue by ttname** [yueyoum/django-siteuser#11]
Internal Server Error: /
Traceback (most recent call last):
  File "/var/www/html/virenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/www/html/virenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/html/virenv/django-siteuser/example/app/views.py", line 32, in home
    users = map(_make_user_info, all_users)
TypeError: argument 2 to map() must support iteration

**Comment by ieiayaobb** [comment]
同样的报错，不知道啥原因
