### ISSUE TITLE
ImportError: cannot import name timedelta_seconds

### ISSUE THREAD

**Issue by Luolired** [yueyoum/django-siteuser#13]
root@Soc:/home/lizx/django-siteuser/example# ./run.sh 
/usr/local/lib/python2.7/dist-packages/kombu/utils/**init**.py:383: UserWarning: Module _yaml was already imported from /usr/lib/python2.7/dist-packages/_yaml.so, but /usr/local/lib/python2.7/dist-packages is being added to sys.path
  from pkg_resources import iter_entry_points
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/**init**.py", line 312, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/**init**.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
  File "/usr/local/lib/python2.7/dist-packages/djcelery/models.py", line 15, in <module>
    from celery.utils.timeutils import timedelta_seconds
ImportError: cannot import name timedelta_seconds

**Comment by yueyoum** [comment]
这个项目好久没更新了

可能新版本的 celery 改的不兼容了吧
